version : "3.7"
services :
  proyectos-micros :
    container_name : proyectos-micros
    image : proyectos-micros:v1
    build :
      context : .
    ports :
      - "4001"
    networks : 
      - proyectos-app
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4001

  proyectos-micros-2 :
    container_name : proyectos-micros-2
    image : proyectos-micros:v1
    ports :
      - "4001"
    networks : 
      - proyectos-app
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4001
  
  loader-balancer:
    container_name : loader-balancer
    image: loader-balancer:v1
    build :
      context : ./loader-balancer
    ports:
      - "4002:80"
    networks : 
      - proyectos-app
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4001    

networks :
  proyectos-app :