version : "3.7"
services :
  proyectos-micros :
    container_name : proyectos-micros
    image : proyectos-micros:v1
    build :
      context : .
    ports :
      - "4001"
    networks : 
      - proyectos-app
    environment:
      - MONGO_URI=mongodb+srv://sebastian1116234435:JGdpCy3FvbOybjoG@cluster0.wh0yrvo.mongodb.net/?retryWrites=true&w=majority
      - PORT=4002

  proyectos-micros-2 :
    container_name : proyectos-micros-2
    image : proyectos-micros:v1
    ports :
      - "4001"
    networks : 
      - proyectos-app
  
  loader-balancer:
    container_name : loader-balancer
    image: loader-balancer:v1
    build :
      context : ./loader-balancer
    ports:
      - "4002:80"
    networks : 
      - proyectos-app


networks :
  proyectos-app :